server:
  port: 8080

spring:
  application:
    name: uranny
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: dumi
    username: dumi
    password: dumi

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    s3:
      bucket: uranny
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: dumi
      secretKey: dumi

jwt:
  secret: dumi